[tools]
rojo = { source = "rojo-rbx/rojo", version = "=7.6.1" }
selene = { source = "Kampfkarren/selene", version = "=0.29.0" }
stylua = { source = "JohnnyMorganz/StyLua", version = "=2.3.1" }
wally = { source = " UpliftGames/wally", version = "=0.3.2" }
