[package]
name = "overhash/abbreviate"
version = "0.0.0"
private = true
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[dev-dependencies]
Jest = "jsdotlua/jest@3.10.0"
JestGlobals = "jsdotlua/jest-globals@3.10.0"
